-- APPLY_012: Položkový rozpočet ul. Moravská (Byt 2+kk) — přesně dle PDF od BOZA REKO s.r.o.
-- Celkem bez DPH: 452 495 Kč | s DPH 12 %: 506 794,4 Kč
-- Spusť v Supabase SQL editoru. Idempotentní: smaže stávající rozpočet projektu a vloží tento.

DO $$
DECLARE
  v_project_id uuid;
BEGIN
  -- Najdi projekt Byt 2+kk (37.53 m2). Uprav WHERE, pokud nesedí.
  SELECT id INTO v_project_id FROM projects
  WHERE name ILIKE '%2+kk%' AND area_m2 = 37.53
  ORDER BY created_at DESC LIMIT 1;

  IF v_project_id IS NULL THEN
    SELECT id INTO v_project_id FROM projects
    WHERE name ILIKE '%2+kk%' ORDER BY created_at DESC LIMIT 1;
  END IF;

  IF v_project_id IS NULL THEN
    RAISE EXCEPTION 'Projekt Byt 2+kk nenalezen - uprav WHERE podminku ve skriptu.';
  END IF;

  -- Odstraň případný existující rozpočet (zabrání duplicitě)
  DELETE FROM budgets WHERE project_id = v_project_id;

  INSERT INTO budgets
    (project_id, name, status, apartment_type, quality_level, area_m2,
     items, total_net, total_gross, margin_percent, notes)
  VALUES (
    v_project_id,
    'Položkový rozpočet — ul. Moravská (2+kk)',
    'approved',
    '2+kk',
    'standard',
    37.53,
    $json$[
  {
    "key": null,
    "dil": "Demontáže a bourací práce",
    "code": "Dem",
    "name": "Demontáž interiérových dveří",
    "unit": "ks",
    "quantity": 5,
    "work_price": 100,
    "material_price": 0,
    "work_total": 500,
    "material_total": 0,
    "total": 500,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Demontáže a bourací práce",
    "code": "Dem",
    "name": "Demontáž ocelové zárubně vč. výřezu betonové příčky",
    "unit": "ks",
    "quantity": 5,
    "work_price": 900,
    "material_price": 0,
    "work_total": 4500,
    "material_total": 0,
    "total": 4500,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Zednické práce",
    "code": "Zed",
    "name": "Zdění z tvárnic YTONG tl. 100 mm",
    "unit": "m2",
    "quantity": 2,
    "work_price": 750,
    "material_price": 0,
    "work_total": 1500,
    "material_total": 0,
    "total": 1500,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Zednické práce",
    "code": "Zed",
    "name": "Obezdění podomítkového WC modulu do výšky 120 cm",
    "unit": "ks",
    "quantity": 1,
    "work_price": 2500,
    "material_price": 0,
    "work_total": 2500,
    "material_total": 0,
    "total": 2500,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Zednické práce",
    "code": "Zed",
    "name": "Úprava výšky a šířky dveřního prostupu přizděním",
    "unit": "ks",
    "quantity": 1,
    "work_price": 3620,
    "material_price": 0,
    "work_total": 3620,
    "material_total": 0,
    "total": 3620,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Zednické práce",
    "code": "Zed",
    "name": "Ukotvení YTONG příčky ke stěně",
    "unit": "ks",
    "quantity": 5,
    "work_price": 100,
    "material_price": 0,
    "work_total": 500,
    "material_total": 0,
    "total": 500,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Zednické práce",
    "code": "Zed",
    "name": "Ukotvení a dilatace YTONG příčky ke stropu montážní pěnou",
    "unit": "bm",
    "quantity": 1,
    "work_price": 250,
    "material_price": 0,
    "work_total": 250,
    "material_total": 0,
    "total": 250,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Zednické práce",
    "code": "Zed",
    "name": "Hrubé zahození drážek maltou",
    "unit": "bm",
    "quantity": 50,
    "work_price": 165,
    "material_price": 0,
    "work_total": 8250,
    "material_total": 0,
    "total": 8250,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Zednické práce",
    "code": "Zed",
    "name": "Natažení lepidla s perlinkou (2 vrstvy, vložená perlinka)",
    "unit": "m2",
    "quantity": 166,
    "work_price": 305,
    "material_price": 0,
    "work_total": 50630,
    "material_total": 0,
    "total": 50630,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Zednické práce",
    "code": "Zed",
    "name": "Penetrace podkladu pod lepidlo s perlinkou",
    "unit": "m2",
    "quantity": 166,
    "work_price": 35,
    "material_price": 0,
    "work_total": 5810,
    "material_total": 0,
    "total": 5810,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Zednické práce",
    "code": "Zed",
    "name": "Penetrace podkladu pod štukovou omítku",
    "unit": "m2",
    "quantity": 120,
    "work_price": 35,
    "material_price": 0,
    "work_total": 4200,
    "material_total": 0,
    "total": 4200,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Zednické práce",
    "code": "Zed",
    "name": "Štukování stěny pytlovým štukem (2 vrstvy + broušení)",
    "unit": "m2",
    "quantity": 120,
    "work_price": 335,
    "material_price": 0,
    "work_total": 40200,
    "material_total": 0,
    "total": 40200,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Zednické práce",
    "code": "Zed",
    "name": "Vybetonování a usazení sprchového žlabu",
    "unit": "ks",
    "quantity": 1,
    "work_price": 3850,
    "material_price": 0,
    "work_total": 3850,
    "material_total": 0,
    "total": 3850,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Sádrokartonářské práce",
    "code": "Sád",
    "name": "Předstěna volně stojící (1x záklop, bez izolace)",
    "unit": "m2",
    "quantity": 1,
    "work_price": 1250,
    "material_price": 0,
    "work_total": 1250,
    "material_total": 0,
    "total": 1250,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Vzduchotechnické práce",
    "code": "VZT",
    "name": "Napojení na stávající VZT stoupačku",
    "unit": "ks",
    "quantity": 1,
    "work_price": 1500,
    "material_price": 0,
    "work_total": 1500,
    "material_total": 0,
    "total": 1500,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Vzduchotechnické práce",
    "code": "VZT",
    "name": "Rozvody vzduchu kulatým potrubím (WC)",
    "unit": "ks",
    "quantity": 3,
    "work_price": 500,
    "material_price": 0,
    "work_total": 1500,
    "material_total": 0,
    "total": 1500,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Obkladačské práce",
    "code": "Obk",
    "name": "Aplikace tekuté hydroizolace (2 vrstvy)",
    "unit": "m2",
    "quantity": 14,
    "work_price": 280,
    "material_price": 0,
    "work_total": 3920,
    "material_total": 0,
    "total": 3920,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Obkladačské práce",
    "code": "Obk",
    "name": "Aplikace hydroizolační koutové pásky",
    "unit": "bm",
    "quantity": 10,
    "work_price": 125,
    "material_price": 0,
    "work_total": 1250,
    "material_total": 0,
    "total": 1250,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Obkladačské práce",
    "code": "Obk",
    "name": "Penetrace podkladu pod obklad",
    "unit": "m2",
    "quantity": 23,
    "work_price": 35,
    "material_price": 0,
    "work_total": 805,
    "material_total": 0,
    "total": 805,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Obkladačské práce",
    "code": "Obk",
    "name": "Montáž keramického obkladu (600×600 mm)",
    "unit": "m2",
    "quantity": 23,
    "work_price": 1200,
    "material_price": 0,
    "work_total": 27600,
    "material_total": 0,
    "total": 27600,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Obkladačské práce",
    "code": "Obk",
    "name": "Penetrace obkladu pod dlažbu",
    "unit": "m2",
    "quantity": 3,
    "work_price": 35,
    "material_price": 0,
    "work_total": 105,
    "material_total": 0,
    "total": 105,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Obkladačské práce",
    "code": "Obk",
    "name": "Montáž keramické dlažby (600×600 mm)",
    "unit": "m2",
    "quantity": 3,
    "work_price": 1200,
    "material_price": 0,
    "work_total": 3600,
    "material_total": 0,
    "total": 3600,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Obkladačské práce",
    "code": "Obk",
    "name": "Vykroužení otvorů",
    "unit": "ks",
    "quantity": 7,
    "work_price": 150,
    "material_price": 0,
    "work_total": 1050,
    "material_total": 0,
    "total": 1050,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Obkladačské práce",
    "code": "Obk",
    "name": "Aplikace silikonu",
    "unit": "bm",
    "quantity": 10,
    "work_price": 45,
    "material_price": 0,
    "work_total": 450,
    "material_total": 0,
    "total": 450,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Obkladačské práce",
    "code": "Obk",
    "name": "Uchycení obkladu na magnety (revizní otvor)",
    "unit": "ks",
    "quantity": 1,
    "work_price": 900,
    "material_price": 0,
    "work_total": 900,
    "material_total": 0,
    "total": 900,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Podlahářské práce",
    "code": "Podl",
    "name": "Penetrace podkladu pod samonivelační stěrku",
    "unit": "m2",
    "quantity": 39,
    "work_price": 40,
    "material_price": 0,
    "work_total": 1560,
    "material_total": 0,
    "total": 1560,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Podlahářské práce",
    "code": "Podl",
    "name": "Aplikace adhézního můstku",
    "unit": "m2",
    "quantity": 16,
    "work_price": 80,
    "material_price": 0,
    "work_total": 1280,
    "material_total": 0,
    "total": 1280,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Podlahářské práce",
    "code": "Podl",
    "name": "Vyrovnání podkladu samonivelační stěrkou do 10 mm",
    "unit": "m2",
    "quantity": 39,
    "work_price": 325,
    "material_price": 0,
    "work_total": 12675,
    "material_total": 0,
    "total": 12675,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Podlahářské práce",
    "code": "Podl",
    "name": "Montáž vinylové podlahy (systém click)",
    "unit": "m2",
    "quantity": 36,
    "work_price": 475,
    "material_price": 0,
    "work_total": 17100,
    "material_total": 0,
    "total": 17100,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Podlahářské práce",
    "code": "Podl",
    "name": "Montáž obvodové krycí lišty",
    "unit": "bm",
    "quantity": 44,
    "work_price": 150,
    "material_price": 0,
    "work_total": 6600,
    "material_total": 0,
    "total": 6600,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Podlahářské práce",
    "code": "Podl",
    "name": "Montáž přechodových lišt popřípadě silikonu",
    "unit": "ks",
    "quantity": 2,
    "work_price": 235,
    "material_price": 0,
    "work_total": 470,
    "material_total": 0,
    "total": 470,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Podlahářské práce",
    "code": "Podl",
    "name": "Aplikace akrylátu mezi soklovou lištou a stěnou",
    "unit": "bm",
    "quantity": 60,
    "work_price": 44,
    "material_price": 0,
    "work_total": 2640,
    "material_total": 0,
    "total": 2640,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Malířské práce",
    "code": "Mal",
    "name": "Penetrace stěny válečkem",
    "unit": "m2",
    "quantity": 120,
    "work_price": 35,
    "material_price": 0,
    "work_total": 4200,
    "material_total": 0,
    "total": 4200,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Malířské práce",
    "code": "Mal",
    "name": "Oškrábání původní výmalby",
    "unit": "m2",
    "quantity": 120,
    "work_price": 80,
    "material_price": 0,
    "work_total": 9600,
    "material_total": 0,
    "total": 9600,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Malířské práce",
    "code": "Mal",
    "name": "Malba stěny",
    "unit": "m2",
    "quantity": 120,
    "work_price": 75,
    "material_price": 0,
    "work_total": 9000,
    "material_total": 0,
    "total": 9000,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Montážní a dokončovací práce",
    "code": "Mont",
    "name": "Dokončovací práce koupelna",
    "unit": "ks",
    "quantity": 1,
    "work_price": 8130,
    "material_price": 0,
    "work_total": 8130,
    "material_total": 0,
    "total": 8130,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Montážní a dokončovací práce",
    "code": "Mont",
    "name": "Dokončovací práce WC",
    "unit": "ks",
    "quantity": 1,
    "work_price": 3500,
    "material_price": 0,
    "work_total": 3500,
    "material_total": 0,
    "total": 3500,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Montážní a dokončovací práce",
    "code": "Mont",
    "name": "Vybroušení + nátěr litinových radiátorů a trubek",
    "unit": "ks",
    "quantity": 1,
    "work_price": 7000,
    "material_price": 0,
    "work_total": 7000,
    "material_total": 0,
    "total": 7000,
    "bundled": false
  },
  {
    "key": null,
    "dil": "TZB — voda, topení",
    "code": "TZB",
    "name": "Voda — nová vodoinstalace, nové rozvody odpadu",
    "unit": "ks",
    "quantity": 1,
    "work_price": 35000,
    "material_price": 0,
    "work_total": 35000,
    "material_total": 0,
    "total": 35000,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Stropy",
    "code": "Str",
    "name": "Montáž napínaných stropů vč. materiálu a světel",
    "unit": "ks",
    "quantity": 1,
    "work_price": 69500,
    "material_price": 0,
    "work_total": 69500,
    "material_total": 0,
    "total": 69500,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Elektrikářské práce",
    "code": "Ele",
    "name": "Vysekání drážek, nové rozvody elektřiny vč. materiálu",
    "unit": "ks",
    "quantity": 1,
    "work_price": 74000,
    "material_price": 0,
    "work_total": 74000,
    "material_total": 0,
    "total": 74000,
    "bundled": false
  },
  {
    "key": null,
    "dil": "Režie",
    "code": "Rež",
    "name": "Doprava pracovníků a materiálu, výnos, likvidace odpadu",
    "unit": "ks",
    "quantity": 1,
    "work_price": 20000,
    "material_price": 0,
    "work_total": 20000,
    "material_total": 0,
    "total": 20000,
    "bundled": false
  }
]$json$::jsonb,
    452495,
    506794.4,
    0,
    'Přesně dle finálního položkového rozpočtu BOZA REKO s.r.o. (ul. Moravská). DPH 12 % (stavební práce pro bydlení).'
  );

  -- Sjednoť souhrn na projektu (zobrazuje se v seznamu projektů)
  UPDATE projects
    SET budget_net = 452495, budget_gross = 506794.4
    WHERE id = v_project_id;

  RAISE NOTICE 'Rozpočet vlozen pro projekt %', v_project_id;
END $$;
